# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Alert < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13 14H11V9H13M13 18H11V16H13M1 21H23L12 2L1 21Z"></path>
      HTML
    end
  end
end
