# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlignVerticalTop
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22 2V4H2V2H22M7 22H10V6H7V22M14 16H17V6H14V16Z"></path>
      HTML
    end
  end
end
