# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.5.95
  # * Author: Google
  class AlignHorizontalCenter < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 2H13V7H21V10H13V14H18V17H13V22H11V17H6V14H11V10H3V7H11V2Z"></path>
      HTML
    end
  end
end
