# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlignVerticalCenter
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22 11H17V6H14V11H10V3H7V11H1.8V13H7V21H10V13H14V18H17V13H22V11Z"></path>
      HTML
    end
  end
end
