# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlignHorizontalDistribute < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4 22H2V2H4V22M22 2H20V22H22V2M13.5 7H10.5V17H13.5V7Z"></path>
      HTML
    end
  end
end
