# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlignVerticalBottom
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22 22H2V20H22V22M10 2H7V18H10V2M17 8H14V18H17V8Z"></path>
      HTML
    end
  end
end
