# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.5.95
  # * Author: Google
  class AlignHorizontalLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4 22H2V2H4V22M22 7H6V10H22V7M16 14H6V17H16V14Z"></path>
      HTML
    end
  end
end
