# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlignHorizontalRight
    def self.content
      <<-HTML.squish.html_safe
        <path d="M20 2H22V22H20V2M2 10H18V7H2V10M8 17H18V14H8V17Z"></path>
      HTML
    end
  end
end
