# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlignVerticalDistribute < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22 2V4H2V2H22M7 10.5V13.5H17V10.5H7M2 20V22H22V20H2Z"></path>
      HTML
    end
  end
end
