# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlphaI < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14,7V9H13V15H14V17H10V15H11V9H10V7H14Z"></path>
      HTML
    end
  end
end
