# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlphaZ
    def self.content
      <<-HTML.squish.html_safe
        <path d="M9,7V9H13L9,15V17H15V15H11L15,9V7H9Z"></path>
      HTML
    end
  end
end
