# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlphaL
    def self.content
      <<-HTML.squish.html_safe
        <path d="M9,7V17H15V15H11V7H9Z"></path>
      HTML
    end
  end
end
