# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.8.94
  # * Author: GreenTurtwig
  class AlphaE < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,7V17H15V15H11V13H15V11H11V9H15V7H9Z"></path>
      HTML
    end
  end
end
