# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlphaT < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,7V9H11V17H13V9H15V7H9Z"></path>
      HTML
    end
  end
end
