# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.2.89
  # * Author: Contributors
  class AlphaNCircle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,7V17H11V12L13,17H15V7H13V12L11,7H9M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2Z"></path>
      HTML
    end
  end
end
