# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.8.94
  # * Author: GreenTurtwig
  class AlphaV < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,7L11,17H13L15,7H13L12,12L11,7H9Z"></path>
      HTML
    end
  end
end
