# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlphaK
    def self.content
      <<-HTML.squish.html_safe
        <path d="M9,7V17H11V13.67L13,17H15L12,12L15,7H13L11,10.33V7H9Z"></path>
      HTML
    end
  end
end
