# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlphaU < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,7V15A2,2 0 0,0 11,17H13A2,2 0 0,0 15,15V7H13V15H11V7H9Z"></path>
      HTML
    end
  end
end
