# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.8.94
  # * Author: GreenTurtwig
  class AlphaN < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,7V17H11V12L13,17H15V7H13V12L11,7H9Z"></path>
      HTML
    end
  end
end
