# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.8.94
  # * Author: GreenTurtwig
  class AlphaA < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11,7A2,2 0 0,0 9,9V17H11V13H13V17H15V9A2,2 0 0,0 13,7H11M11,9H13V11H11V9Z"></path>
      HTML
    end
  end
end
