# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AlphaH < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,7V17H11V13H13V17H15V7H13V11H11V7H9Z"></path>
      HTML
    end
  end
end
