# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AngleRight
    def self.content
      <<-HTML.squish.html_safe
        <path d="M5,4H7V11H13V17H20V19H5V4M7,17H11V13H7V17Z"></path>
      HTML
    end
  end
end
