# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.6.50
  # * Author: Austin Andrews
  class AppleKeyboardControl < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19.78,11.78L18.36,13.19L12,6.83L5.64,13.19L4.22,11.78L12,4L19.78,11.78Z"></path>
      HTML
    end
  end
end
