# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class AppleKeyboardOption
    def self.content
      <<-HTML.squish.html_safe
        <path d="M3,4H9.11L16.15,18H21V20H14.88L7.84,6H3V4M14,4H21V6H14V4Z"></path>
      HTML
    end
  end
end
