# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.6.50
  # * Author: Austin Andrews
  class ApplicationOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21 2H3C1.9 2 1 2.9 1 4V20C1 21.1 1.9 22 3 22H21C22.1 22 23 21.1 23 20V4C23 2.9 22.1 2 21 2M21 20H3V6H21V20Z"></path>
      HTML
    end
  end
end
