# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.7.95
  # * Author: frankgrinaert
  class ArchiveArrowUpOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20 21H4V10H6V19H18V10H20V21M3 3H21V9H3V3M5 5V7H19V5M10.5 17V14H8L12 10L16 14H13.5V17"></path>
      HTML
    end
  end
end
