# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArchiveArrowUp < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4 21H20V8H4M14 15V18H10V15H7L12 10L17 15M3 3H21V7H3"></path>
      HTML
    end
  end
end
