# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArchiveArrowDown < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 3H21V7H3V3M4 21V8H20V21H4M14 14V11H10V14H7L12 19L17 14H14Z"></path>
      HTML
    end
  end
end
