# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowBottomRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,6.41L6.41,5L17,15.59V9H19V19H9V17H15.59L5,6.41Z"></path>
      HTML
    end
  end
end
