# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.0.46
  # * Author: Michael Richins
  class ArrowExpandDown < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22,4V2H2V4H11V18.17L5.5,12.67L4.08,14.08L12,22L19.92,14.08L18.5,12.67L13,18.17V4H22Z"></path>
      HTML
    end
  end
end
