# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowLeftBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20,9V15H12V19.84L4.16,12L12,4.16V9H20Z"></path>
      HTML
    end
  end
end
