# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Austin Andrews
  class ArrowTopRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,17.59L15.59,7H9V5H19V15H17V8.41L6.41,19L5,17.59Z"></path>
      HTML
    end
  end
end
