# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.9.32
  # * Author: Austin Andrews
  class ArrowDownBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,4H15V12H19.84L12,19.84L4.16,12H9V4Z"></path>
      HTML
    end
  end
end
