# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowTopRightBottomLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11,21H3V13H5V17.59L17.59,5H13V3H21V11H19V6.41L6.41,19H11V21Z"></path>
      HTML
    end
  end
end
