# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowDownBoldOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22,11L12,21L2,11H8V3H16V11H22M12,18L17,13H14V5H10V13H7L12,18Z"></path>
      HTML
    end
  end
end
