# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.5.95
  # * Author: Matt Stayner
  class ArrowUpThin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7.03 9.97H11.03V18.89L13.04 18.92V9.97H17.03L12.03 4.97Z"></path>
      HTML
    end
  end
end
