# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowBottomRightThin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11.93 19L14.76 16.18L5 6.42L6.42 5L16.18 14.76L19 11.94V19Z"></path>
      HTML
    end
  end
end
