# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: Michael Irigoyen
  class ArrowTopLeftThick < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9.12,11.94V16.89H5.69V5.69H16.89V9.12H11.94L18.31,15.5L15.5,18.31L9.12,11.94Z"></path>
      HTML
    end
  end
end
