# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowTopLeftBottomRightBold
    def self.content
      <<-HTML.squish.html_safe
        <path d="M5.83,8.66L3,11.5V3H11.5L8.66,5.83L18.17,15.34L21,12.5V21H12.5L15.34,18.17L5.83,8.66Z"></path>
      HTML
    end
  end
end
