# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowLeftRightBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8,14V18L2,12L8,6V10H16V6L22,12L16,18V14H8Z"></path>
      HTML
    end
  end
end
