# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowTopRightThin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11.93 5L14.76 7.83L5 17.59L6.42 19L16.18 9.25L19 12.07V5H11.93Z"></path>
      HTML
    end
  end
end
