# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.5.95
  # * Author: Matt Stayner
  class ArrowTopLeftThin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12.07 5L9.24 7.83L19 17.59L17.58 19L7.82 9.25L5 12.07V5Z"></path>
      HTML
    end
  end
end
