# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.1.99
  # * Author: Google
  class ArrowCollapseVertical < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,12H20V14H4V12M4,9H20V11H4V9M16,4L12,8L8,4H11V1H13V4H16M8,19L12,15L16,19H13V22H11V19H8Z"></path>
      HTML
    end
  end
end
