# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowUpBoldOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M16,13V21H8V13H2L12,3L22,13H16M7,11H10V19H14V11H17L12,6L7,11Z"></path>
      HTML
    end
  end
end
