# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: Michael Irigoyen
  class ArrowLeftBoldOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13,22L3,12L13,2V8H21V16H13V22M6,12L11,17V14H19V10H11V7L6,12Z"></path>
      HTML
    end
  end
end
