# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.7.94
  # * Author: Austin Andrews
  class ArrowUpDownBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10,8H6L12,2L18,8H14V16H18L12,22L6,16H10V8Z"></path>
      HTML
    end
  end
end
