# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowRightBoldOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11,16H3V8H11V2L21,12L11,22V16M13,7V10H5V14H13V17L18,12L13,7Z"></path>
      HTML
    end
  end
end
