# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowUpBold
    def self.content
      <<-HTML.squish.html_safe
        <path d="M15,20H9V12H4.16L12,4.16L19.84,12H15V20Z"></path>
      HTML
    end
  end
end
