# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowRightThin
    def self.content
      <<-HTML.squish.html_safe
        <path d="M14 16.94V12.94H5.08L5.05 10.93H14V6.94L19 11.94Z"></path>
      HTML
    end
  end
end
