# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowDownBold
    def self.content
      <<-HTML.squish.html_safe
        <path d="M9,4H15V12H19.84L12,19.84L4.16,12H9V4Z"></path>
      HTML
    end
  end
end
