# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.5.95
  # * Author: Matt Stayner
  class ArrowDownThin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7.03 13.92H11.03V5L13.04 4.97V13.92H17.03L12.03 18.92Z"></path>
      HTML
    end
  end
end
