# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.5.95
  # * Author: Matt Stayner
  class ArrowLeftThin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10.05 16.94V12.94H18.97L19 10.93H10.05V6.94L5.05 11.94Z"></path>
      HTML
    end
  end
end
