# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.5.95
  # * Author: Matt Stayner
  class ArrowBottomLeftThin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12.07 19L9.24 16.18L19 6.42L17.58 5L7.82 14.76L5 11.94V19Z"></path>
      HTML
    end
  end
end
