# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Austin Andrews
  class ArrowTopLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,17.59L17.59,19L7,8.41V15H5V5H15V7H8.41L19,17.59Z"></path>
      HTML
    end
  end
end
