# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.1.95
  # * Author: Colton Wiscombe
  class ArrowURightTopBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 13.5C3 9.36 6.36 6 10.5 6H13V2L20 8L13 14V10H10.5C8.57 10 7 11.57 7 13.5S8.57 17 10.5 17H18V21H10.5C6.36 21 3 17.64 3 13.5Z"></path>
      HTML
    end
  end
end
