# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: Michael Irigoyen
  class ArrowBottomLeftThick < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M15.5,5.69L18.31,8.5L11.94,14.89H16.89V18.31H5.69V7.11H9.12V12.06L15.5,5.69Z"></path>
      HTML
    end
  end
end
