# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.9.32
  # * Author: Austin Andrews
  class ArrowRightBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,15V9H12V4.16L19.84,12L12,19.84V15H4Z"></path>
      HTML
    end
  end
end
