# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.9.32
  # * Author: Austin Andrews
  class ArrowLeftBoldBox < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21,5V19A2,2 0 0,1 19,21H5A2,2 0 0,1 3,19V5A2,2 0 0,1 5,3H19A2,2 0 0,1 21,5M7,12L12,17V14H16V10H12V7L7,12Z"></path>
      HTML
    end
  end
end
