# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowBottomLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,6.41L17.59,5L7,15.59V9H5V19H15V17H8.41L19,6.41Z"></path>
      HTML
    end
  end
end
