# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.1.95
  # * Author: Colton Wiscombe
  class ArrowRightBottomBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 3H7V10.5C7 12.43 8.57 14 10.5 14H13V10L20 16L13 22V18H10.5C6.36 18 3 14.64 3 10.5V3Z"></path>
      HTML
    end
  end
end
