# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.7.94
  # * Author: Austin Andrews
  class ArrowTopRightBottomLeftBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18.17,8.66L21,11.5V3H12.5L15.34,5.83L5.83,15.34L3,12.5V21H11.5L8.66,18.17L18.17,8.66Z"></path>
      HTML
    end
  end
end
