# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowTopLeftBottomRight
    def self.content
      <<-HTML.squish.html_safe
        <path d="M13,21H21V13H19V17.59L6.41,5H11V3H3V11H5V6.41L17.59,19H13V21Z"></path>
      HTML
    end
  end
end
