# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowBottomRightThick < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14.89,12.06V7.11H18.31V18.31H7.11V14.89H12.06L5.69,8.5L8.5,5.69L14.89,12.06Z"></path>
      HTML
    end
  end
end
