# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.0.46
  # * Author: Michael Richins
  class ArrowExpandRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,2H2V22H4V13H18.17L12.67,18.5L14.08,19.92L22,12L14.08,4.08L12.67,5.5L18.17,11H4V2Z"></path>
      HTML
    end
  end
end
