# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.1.99
  # * Author: Google
  class ArrowCollapseHorizontal < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13,20V4H15.03V20H13M10,20V4H12.03V20H10M5,8L9.03,12L5,16V13H2V11H5V8M20,16L16,12L20,8V11H23V13H20V16Z"></path>
      HTML
    end
  end
end
