# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ArrowLeftBottomBold
    def self.content
      <<-HTML.squish.html_safe
        <path d="M21 10.5C21 14.64 17.64 18 13.5 18H11V22L4 16L11 10V14H13.5C15.43 14 17 12.43 17 10.5V3H21V10.5Z"></path>
      HTML
    end
  end
end
