# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.4.93
  # * Author: Austin Andrews
  class AxisXArrow < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M1.5,20.5L3,15.03L4.46,17.6L11,13.82V3H13V13.82L22.39,19.25L21.39,21L12,15.56L5.46,19.33L7,21.96L1.5,20.5Z"></path>
      HTML
    end
  end
end
