# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.2.43
  # * Author: GreenTurtwig
  class BedEmpty < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,7H5V14H3V5H1V20H3V17H21V20H23V11A4,4 0 0,0 19,7"></path>
      HTML
    end
  end
end
