# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class BlindsVertical
    def self.content
      <<-HTML.squish.html_safe
        <path d="M20 19V3H4V19H2V21H22V19H20M10 19V5H14V19H10Z"></path>
      HTML
    end
  end
end
