# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class BookmarkMinus < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M17,3H7A2,2 0 0,0 5,5V21L12,18L19,21V5A2,2 0 0,0 17,3M15,11H9V9H15V11Z"></path>
      HTML
    end
  end
end
