# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.7.95
  # * Author: Thomas de Saint-Exupéry
  class Bookshelf < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9 3V18H12V3H9M12 5L16 18L19 17L15 4L12 5M5 5V18H8V5H5M3 19V21H21V19H3Z"></path>
      HTML
    end
  end
end
