# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.2.43
  # * Author: Austin Andrews
  class BorderAllVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,21V3H21V21H3M5,5V19H19V5H5Z"></path>
      HTML
    end
  end
end
