# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class BowTie < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M15,14L21,17V7L15,10V14M9,14L3,17V7L9,10V14M10,10H14V14H10V10Z"></path>
      HTML
    end
  end
end
