# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Bowl
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22 15C22 18.9 18.9 22 15 22H9C5.1 22 2 18.9 2 15V12H22V15Z"></path>
      HTML
    end
  end
end
