# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class BucketOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 4H21V7H20L17.5 21H6.5L4 7H3V4M17.97 7H6.03L8.15 19H15.85L17.97 7Z"></path>
      HTML
    end
  end
end
