# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Bucket
    def self.content
      <<-HTML.squish.html_safe
        <path d="M3 4H21V7H20L17.5 21H6.5L4 7H3V4Z"></path>
      HTML
    end
  end
end
