# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class CallReceived < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20,5.41L18.59,4L7,15.59V9H5V19H15V17H8.41"></path>
      HTML
    end
  end
end
