# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class CallMade
    def self.content
      <<-HTML.squish.html_safe
        <path d="M9,5V7H15.59L4,18.59L5.41,20L17,8.41V15H19V5"></path>
      HTML
    end
  end
end
