# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class CardsDiamondOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 2L5 12L12 22L19 12M7.44 12L12 5.5L16.56 12L12 18.5"></path>
      HTML
    end
  end
end
