# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.0.39
  # * Author: Rynco Li
  class Card < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20,20H4A2,2 0 0,1 2,18V6A2,2 0 0,1 4,4H20A2,2 0 0,1 22,6V18A2,2 0 0,1 20,20Z"></path>
      HTML
    end
  end
end
