# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class CardsDiamond
    def self.content
      <<-HTML.squish.html_safe
        <path d="M19,12L12,22L5,12L12,2"></path>
      HTML
    end
  end
end
