# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.1.95
  # * Author: Teodor Sandu
  class CeilingLightOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14.76 11L16.76 15H7.24L9.24 11H14.76M13 4H11V9H8L4 17H20L16 9H13V4M14 18H10C10 19.11 10.9 20 12 20S14 19.11 14 18Z"></path>
      HTML
    end
  end
end
