# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Austin Andrews
  class ChartHistogram < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,3H5V13H9V7H13V11H17V15H21V21H3V3Z"></path>
      HTML
    end
  end
end
