# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.0.46
  # * Author: Google
  class ChartLineVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3.5,18.5L9.5,12.5L13.5,16.5L22,6.92L20.59,5.5L13.5,13.5L9.5,9.5L2,17L3.5,18.5Z"></path>
      HTML
    end
  end
end
