# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.7.94
  # * Author: Michael Richins
  class ChartAreasplineVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22,21H2V3H4V15.54L9.5,6L16,9.78L20.24,2.45L21.97,3.45L22,21Z"></path>
      HTML
    end
  end
end
