# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ChartBar
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22,21H2V3H4V19H6V10H10V19H12V6H16V19H18V14H22V21Z"></path>
      HTML
    end
  end
end
