# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.7.94
  # * Author: Google
  class Checkbook < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,14H19V15H5V14M21,17V8H3V17H21M1,5H23V19H1V5M5,10H12V12H5V10Z"></path>
      HTML
    end
  end
end
