# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.6.95
  # * Author: Austin Andrews
  class CheckUnderline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21,5L9,17L3.5,11.5L4.91,10.09L9,14.17L19.59,3.59L21,5M3,21V19H21V21H3Z"></path>
      HTML
    end
  end
end
