# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.1.99
  # * Author: Michael Richins
  class ChessRook < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,20H19V22H5V20M17,2V5H15V2H13V5H11V2H9V5H7V2H5V8H7V18H17V8H19V2H17Z"></path>
      HTML
    end
  end
end
