# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: Michael Irigoyen
  class CircleSmall < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,10A2,2 0 0,0 10,12C10,13.11 10.9,14 12,14C13.11,14 14,13.11 14,12A2,2 0 0,0 12,10Z"></path>
      HTML
    end
  end
end
