# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.0.45
  # * Author: Simran
  class CircleHalf < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 2A10 10 0 0 0 2 12A10 10 0 0 0 12 22V2Z"></path>
      HTML
    end
  end
end
