# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.2.45
  # * Author: Michael Irigoyen
  class ClockTimeSeven < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 2C6.5 2 2 6.5 2 12C2 17.5 6.5 22 12 22C17.5 22 22 17.5 22 12S17.5 2 12 2M12.5 12.2L9.8 17L8.5 16.2L11 11.8V7H12.5V12.2Z"></path>
      HTML
    end
  end
end
