# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class CodeBrackets
    def self.content
      <<-HTML.squish.html_safe
        <path d="M15,4V6H18V18H15V20H20V4M4,4V20H9V18H6V6H9V4H4Z"></path>
      HTML
    end
  end
end
