# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.0.39
  # * Author: Michael Irigoyen
  class Coffin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8,22L5,8L8,2H16L19,8L16,22H8M11,6V8H9V10H11V15H13V10H15V8H13V6H11Z"></path>
      HTML
    end
  end
end
