# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ColorHelper < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M0,24H24V20H0V24Z"></path>
      HTML
    end
  end
end
