# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.6.95
  # * Author: Michael Richins
  class Comma < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,3H16.95V12.96L12.96,20.94H8L11.97,12.96H7V3Z"></path>
      HTML
    end
  end
end
