# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class CompareVertical < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14 15V22H16V15H19L15 11L11 15H14M13 9H10V2H8V9H5L9 13L13 9Z"></path>
      HTML
    end
  end
end
