# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class CompareHorizontal < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9 14H2V16H9V19L13 15L9 11V14M15 13V10H22V8H15V5L11 9L15 13Z"></path>
      HTML
    end
  end
end
