# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.6.95
  # * Author: Michael Richins
  class ContainStart < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2,3H8V5H4V19H8V21H2V3M7,17V15H9V17H7M11,17V15H13V17H11M15,17V15H17V17H15Z"></path>
      HTML
    end
  end
end
