# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ContainEnd < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,17V15H9V17H7M11,17V15H13V17H11M15,17V15H17V17H15M22,3V21H16V19H20V5H16V3H22Z"></path>
      HTML
    end
  end
end
