# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Cross
    def self.content
      <<-HTML.squish.html_safe
        <path d="M10.5,2H13.5V8H19V11H13.5V22H10.5V11H5V8H10.5V2Z"></path>
      HTML
    end
  end
end
