# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.4.85
  # * Author: Nick
  class CurrentDc < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2,9V11H22V9H2M2,13V15H7V13H2M9,13V15H15V13H9M17,13V15H22V13H17Z"></path>
      HTML
    end
  end
end
