# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.0.46
  # * Author: Haley Halcyon
  class CurrencyTwd < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,11H21V13H15V19H21V21H15A2,2 0 0,1 13,19V13H10.35L5.73,21L4,20L8.04,13H3V11M5,3H19V5H5V3Z"></path>
      HTML
    end
  end
end
