# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.7.96
  # * Author: Google
  class CurrencyFra < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18 5V3H7V16H5V18H7V21H9V18H13V16H9V13H17V11H9V5H18Z"></path>
      HTML
    end
  end
end
