# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.0.46
  # * Author: Google
  class CurrencyJpy < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13.92 11H18V13H13V15H18V17H13V21H11V17H6V15H11V13H6V11H10.08L5 3H7.37L12 10.29L16.63 3H19L13.92 11Z"></path>
      HTML
    end
  end
end
