# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.1.99
  # * Author: Augustin Ursu
  class CurrencyKzt < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,3H19V5H5V3M5,6H19V8H13V21H11V8H5V6Z"></path>
      HTML
    end
  end
end
