# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class CurrencyEth < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,5H18V7H6M7,11H17V13H7M5.5,17H18.5V19H5.5"></path>
      HTML
    end
  end
end
