# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.2.95
  # * Author: Teodor Sandu
  class CurtainsClosed < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M23 3H1V1H23V3M2 22H11V4H2V22M22 4H13V22H22V4Z"></path>
      HTML
    end
  end
end
