# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class Delta < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,7.77L18.39,18H5.61L12,7.77M12,4L2,20H22"></path>
      HTML
    end
  end
end
