# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class Details < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6.38,6H17.63L12,16L6.38,6M3,4L12,20L21,4H3Z"></path>
      HTML
    end
  end
end
