# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Deviantart < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,6H12L14,2H18V6L14.5,13H18V18H12L10,22H6V18L9.5,11H6V6Z"></path>
      HTML
    end
  end
end
