# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Diamond < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,2L2,8L12,22L22,8L18,2H6Z"></path>
      HTML
    end
  end
end
