# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class DistributeVerticalCenter
    def self.content
      <<-HTML.squish.html_safe
        <path d="M2 16H5V14H19V16H22V18H19V20H5V18H2V16M2 8H7V10H17V8H22V6H17V4H7V6H2V8Z"></path>
      HTML
    end
  end
end
