# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.5.95
  # * Author: Michael Irigoyen
  class DistributeHorizontalRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 17V7H8V2H10V22H8V17H3M19 22H21V2H19V5H14V19H19V22Z"></path>
      HTML
    end
  end
end
