# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class DistributeHorizontalLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21 7V17H16V22H14V2H16V7H21M5 2H3V22H5V19H10V5H5V2Z"></path>
      HTML
    end
  end
end
