# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.5.95
  # * Author: Michael Irigoyen
  class DistributeHorizontalCenter < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8 2V5H10V19H8V22H6V19H4V5H6V2H8M16 2V7H14V17H16V22H18V17H20V7H18V2H16Z"></path>
      HTML
    end
  end
end
