# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.5.95
  # * Author: Michael Irigoyen
  class DistributeVerticalBottom < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7 3H17V8H22V10H2V8H7V3M2 19V21H22V19H19V14H5V19H2Z"></path>
      HTML
    end
  end
end
