# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class DistributeVerticalTop < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M17 21H7V16H2V14H22V16H17V21M22 5V3H2V5H5V10H19V5H22Z"></path>
      HTML
    end
  end
end
