# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.5.94
  # * Author: Michael Richins
  class DivingScubaFlag < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2,6L19,20H2V6M5,4L22,18V4H5Z"></path>
      HTML
    end
  end
end
