# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.2.95
  # * Author: Michael Richins
  class DockRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20 4H4A2 2 0 0 0 2 6V18A2 2 0 0 0 4 20H20A2 2 0 0 0 22 18V6A2 2 0 0 0 20 4M15 18H4V6H15Z"></path>
      HTML
    end
  end
end
