# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class Download < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,20H19V18H5M19,9H15V3H9V9H5L12,16L19,9Z"></path>
      HTML
    end
  end
end
