# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: GreenTurtwig
  class DownloadMultiple < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,1V7H5L12,14L19,7H15V1H9M5,16V18H19V16H5M5,20V22H19V20H5Z"></path>
      HTML
    end
  end
end
