# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class DragHorizontalVariant
    def self.content
      <<-HTML.squish.html_safe
        <path d="M21 11H3V9H21V11M21 13H3V15H21V13Z"></path>
      HTML
    end
  end
end
