# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class DragVerticalVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 21H9V3H11V21M15 3H13V21H15V3Z"></path>
      HTML
    end
  end
end
