# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Eject
    def self.content
      <<-HTML.squish.html_safe
        <path d="M12,5L5.33,15H18.67M5,17H19V19H5V17Z"></path>
      HTML
    end
  end
end
