# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.0.39
  # * Author: Google
  class EjectOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,17H19V19H5V17M12,5L5.33,15H18.67L12,5M12,8.6L14.93,13H9.07L12,8.6Z"></path>
      HTML
    end
  end
end
