# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.7.94
  # * Author: Michael Richins
  class Ellipse < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,4C6.5,4 2,7.58 2,12C2,16.42 6.5,20 12,20C17.5,20 22,16.42 22,12C22,7.58 17.5,4 12,4Z"></path>
      HTML
    end
  end
end
