# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Equal
    def self.content
      <<-HTML.squish.html_safe
        <path d="M19,10H5V8H19V10M19,16H5V14H19V16Z"></path>
      HTML
    end
  end
end
