# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Equalizer
    def self.content
      <<-HTML.squish.html_safe
        <path d="M10,20H14V4H10V20M4,20H8V12H4V20M16,9V20H20V9H16Z"></path>
      HTML
    end
  end
end
