# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Simran
  class EthernetCable < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11,3V7H13V3H11M8,4V11H16V4H14V8H10V4H8M10,12V22H14V12H10Z"></path>
      HTML
    end
  end
end
