# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.6.95
  # * Author: frankgrinaert
  class ExclamationThick < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10 3H14V14H10V3M10 21V17H14V21H10Z"></path>
      HTML
    end
  end
end
