# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FacebookGaming < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9.5 14.5V9.5H21V21H15.5V14.5H9.5M3 3H21L21 8.5H8.5V15.5H14.5V21H3V3Z"></path>
      HTML
    end
  end
end
