# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FastForward
    def self.content
      <<-HTML.squish.html_safe
        <path d="M13,6V18L21.5,12M4,18L12.5,12L4,6V18Z"></path>
      HTML
    end
  end
end
