# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FilterVariant
    def self.content
      <<-HTML.squish.html_safe
        <path d="M6,13H18V11H6M3,6V8H21V6M10,18H14V16H10V18Z"></path>
      HTML
    end
  end
end
