# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.6.95
  # * Author: Michael Irigoyen
  class FireplaceOff < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22,22H2V20H22V22M22,6H2V3H22V6M20,7V19H17V11C17,11 14.5,10 12,10C9.5,10 7,11 7,11V19H4V7H20Z"></path>
      HTML
    end
  end
end
