# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class Flag < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"></path>
      HTML
    end
  end
end
