# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FlagMinus
    def self.content
      <<-HTML.squish.html_safe
        <path d="M12.4,5H18V15H11L10.6,13H5V20H3V3H12L12.4,5M14,17H22V19H14V17Z"></path>
      HTML
    end
  end
end
