# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FlagTriangle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,2H9V22H7V2M19,9L11,14.6V3.4L19,9Z"></path>
      HTML
    end
  end
end
