# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Flash < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,2V13H10V22L17,10H13L17,2H7Z"></path>
      HTML
    end
  end
end
