# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.9.96
  # * Author: tetzla
  class FlashTriangle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 2L1 21H23L12 2M10 15V10H14L12.5 13.5H14.5L11.5 19V15H10Z"></path>
      HTML
    end
  end
end
