# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.8.36
  # * Author: Michael Irigoyen
  class FlashOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,2H17L13.5,9H17L10,22V14H7V2M9,4V12H12V14.66L14,11H10.24L13.76,4H9Z"></path>
      HTML
    end
  end
end
