# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.8.95
  # * Author: Michael Irigoyen
  class FlashAlert < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,2V13H8V22L15,10H11L15,2M17,15H19V17H17V15M17,7H19V13H17V7Z"></path>
      HTML
    end
  end
end
