# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.9.96
  # * Author: tetzla
  class FlashTriangleOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 2L1 21H23M12 6L19.5 19H4.5M14 14H12.5L14 11H10V15H11V18L14 14Z"></path>
      HTML
    end
  end
end
