# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.3.50
  # * Author: GreenTurtwig
  class FloorLamp < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M15,2L17,9H7L9,2M11,10H13V20H16V22H8V20H11V10Z"></path>
      HTML
    end
  end
end
