# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.1.95
  # * Author: Borre Haugen
  class FloorLampTorchiereVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7 2L10 9H14L17 2H7M15.92 22L13 15V22H11V15L8.08 22H5.92L10.92 10H13.08L18.08 22H15.92Z"></path>
      HTML
    end
  end
end
