# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FloorLampOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M15 2L17 9H7L9 2M13.6 4H10.4L9.55 7H14.45M11 10H13V20H16V22H8V20H11Z"></path>
      HTML
    end
  end
end
