# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FloorLampTorchiere < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7 2L10 9H14L17 2H7M13 20H16V22H8V20H11V10H13V20Z"></path>
      HTML
    end
  end
end
