# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FloorLampTorchiereOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14 4L12.7 7H11.3L10 4H14M17 2H7L10 9H14L17 2M13 20H16V22H8V20H11V10H13V20Z"></path>
      HTML
    end
  end
end
