# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.0.46
  # * Author: Alex Efremo
  class FoodCroissant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22,19L19,17L22,15V19M15,15L19,9L22,13L18,16L15,15M5,17L2,19V15L5,17M9,15L6,16L2,13L5,9L9,15M14,6L18,8L13,15H11L6,8L10,6H14Z"></path>
      HTML
    end
  end
end
