# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.6.50
  # * Author: Austin Andrews
  class FormatHorizontalAlignRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13,8V11H3V13H13V16L17,12L13,8M19,20H21V4H19V20Z"></path>
      HTML
    end
  end
end
