# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FormatVerticalAlignCenter
    def self.content
      <<-HTML.squish.html_safe
        <path d="M8,19H11V23H13V19H16L12,15L8,19M16,5H13V1H11V5H8L12,9L16,5M4,11V13H20V11H4Z"></path>
      HTML
    end
  end
end
