# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FormatTitle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,4V7H10.5V19H13.5V7H19V4H5Z"></path>
      HTML
    end
  end
end
