# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Andreas Gohr
  class FormatFloatLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,7H9V13H3V7M3,3H21V5H3V3M21,7V9H11V7H21M21,11V13H11V11H21M3,15H17V17H3V15M3,19H21V21H3V19Z"></path>
      HTML
    end
  end
end
