# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.7.12
  # * Author: Google
  class FormatColorText < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9.62,12L12,5.67L14.37,12M11,3L5.5,17H7.75L8.87,14H15.12L16.25,17H18.5L13,3H11Z"></path>
      HTML
    end
  end
end
