# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.6.50
  # * Author: Google
  class FormatVerticalAlignTop < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8,11H11V21H13V11H16L12,7L8,11M4,3V5H20V3H4Z"></path>
      HTML
    end
  end
end
