# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FormatTextVariant
    def self.content
      <<-HTML.squish.html_safe
        <path d="M9.6,14L12,7.7L14.4,14M11,5L5.5,19H7.7L8.8,16H15L16.1,19H18.3L13,5H11Z"></path>
      HTML
    end
  end
end
