# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.6.50
  # * Author: Austin Andrews
  class FormatHorizontalAlignCenter < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,16V13H23V11H19V8L15,12L19,16M5,8V11H1V13H5V16L9,12L5,8M11,20H13V4H11V20Z"></path>
      HTML
    end
  end
end
