# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.9.32
  # * Author: Austin Andrews
  class FormatAlignBottom < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13,9L15.5,6.5L16.92,7.92L12,12.84L7.08,7.92L8.5,6.5L11,9V3H13V9M3,15H21V17H3V15M3,19H13V21H3V19Z"></path>
      HTML
    end
  end
end
