# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.9.96
  # * Author: Sintija
  class FormatParagraphSpacing < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 17H21V19H3V17M3 2H21V4H3V2M3 20H21V22H3V20M13 8H15L12 5L9 8H11V13H9L12 16L15 13H13V8Z"></path>
      HTML
    end
  end
end
