# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FormatSize < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2 4V7H7V19H10V7H15V4H2M21 9H12V12H15V19H18V12H21V9Z"></path>
      HTML
    end
  end
end
