# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FormatLineWeight
    def self.content
      <<-HTML.squish.html_safe
        <path d="M3,17H21V15H3V17M3,20H21V19H3V20M3,13H21V10H3V13M3,4V8H21V4H3Z"></path>
      HTML
    end
  end
end
