# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FormatHeaderEqual
    def self.content
      <<-HTML.squish.html_safe
        <path d="M4,4H6V10H10V4H12V18H10V12H6V18H4V4M14,10V8H21V10H14M14,12H21V14H14V12Z"></path>
      HTML
    end
  end
end
