# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FormatTextWrappingOverflow < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,21H5V3H7V21M14,3H12V9H14V3M14,15H12V21H14V15M19,12L16,9V11H9V13H16V15L19,12Z"></path>
      HTML
    end
  end
end
