# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.6.50
  # * Author: Austin Andrews
  class FormatHorizontalAlignLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11,16V13H21V11H11V8L7,12L11,16M3,20H5V4H3V20Z"></path>
      HTML
    end
  end
end
