# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.5.94
  # * Author: Google
  class FormatListBulletedSquare < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,4H7V8H3V4M9,5V7H21V5H9M3,10H7V14H3V10M9,11V13H21V11H9M3,16H7V20H3V16M9,17V19H21V17H9"></path>
      HTML
    end
  end
end
