# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Andreas Gohr
  class FormatWrapTopBottom < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,7L17,17H7L12,7M3,3H21V5H3V3M3,19H21V21H3V19Z"></path>
      HTML
    end
  end
end
