# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class FormatVerticalAlignBottom < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M16,13H13V3H11V13H8L12,17L16,13M4,19V21H20V19H4Z"></path>
      HTML
    end
  end
end
