# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Forward
    def self.content
      <<-HTML.squish.html_safe
        <path d="M12,8V4L20,12L12,20V16H4V8H12Z"></path>
      HTML
    end
  end
end
