# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.8.95
  # * Author: Michael Irigoyen
  class GarageAlertVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20 9V20H18V11H2V20H0V9L10 5L20 9M17 12H3V14H17V12M17 15H3V17H17V15M22 15V10H24V15H22M22 19V17H24V19H22Z"></path>
      HTML
    end
  end
end
