# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.8.95
  # * Author: Michael Irigoyen
  class GarageOpenVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22 9V20H20V11H4V20H2V9L12 5L22 9M19 12H5V14H19V12Z"></path>
      HTML
    end
  end
end
