# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class GarageOpenVariant
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22 9V20H20V11H4V20H2V9L12 5L22 9M19 12H5V14H19V12Z"></path>
      HTML
    end
  end
end
