# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.9.96
  # * Author: Michael Irigoyen
  class GateBuffer < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6 7.24L15.53 12L6 16.76V7.24M4 4V20L20 12L4 4Z"></path>
      HTML
    end
  end
end
