# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Austin Andrews
  class GlassStange < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8,2H16V22H8V2M10,4V7H14V4H10Z"></path>
      HTML
    end
  end
end
