# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class GlassPintOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M4 2L6 22H17L19 2H4M6.2 4H16.8L15.2 20H7.8L6.2 4Z"></path>
      HTML
    end
  end
end
