# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.4.85
  # * Author: Nick
  class GreaterThan < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5.5,4.14L4.5,5.86L15,12L4.5,18.14L5.5,19.86L19,12L5.5,4.14Z"></path>
      HTML
    end
  end
end
