# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.7.94
  # * Author: Michael Irigoyen
  class Hexagram < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14.5,7.66L20.64,6.97L17,12L20.68,16.97L14.5,16.32L12.03,22L9.5,16.34L3.36,17.03L7,12L3.32,7.03L9.5,7.68L11.97,2L14.5,7.66Z"></path>
      HTML
    end
  end
end
