# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class HomeVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,3L20,9V21H15V14H9V21H4V9L12,3Z"></path>
      HTML
    end
  end
end
