# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.9.97
  # * Author: Michael Irigoyen
  class HomeExportOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M24 13L20 17V14H11V12H20V9L24 13M4 20V12H1L11 3L18 9.3V10H15.79L11 5.69L6 10.19V18H16V16H18V20H4Z"></path>
      HTML
    end
  end
end
