# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.4.95
  # * Author: Michael Irigoyen
  class HomeLightningBolt < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 3L2 12H5V20H19V12H22L12 3M11.5 18V14H9L12.5 7V11H15L11.5 18Z"></path>
      HTML
    end
  end
end
