# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class HomeRoof < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19 16H22L12 7L2 16H5L12 9.69L19 16M7 8.81V7H4V11.5L7 8.81Z"></path>
      HTML
    end
  end
end
