# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.5.94
  # * Author: Michael Irigoyen
  class HomeFloorNegative1 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,3L2,12H5V20H19V12H22L12,3M11,15H7V13H11V15M15,18H13V10H11V8H15V18Z"></path>
      HTML
    end
  end
end
