# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class HomeFloorL
    def self.content
      <<-HTML.squish.html_safe
        <path d="M12,3L2,12H5V20H19V12H22L12,3M9,8H11V16H15V18H9V8Z"></path>
      HTML
    end
  end
end
