# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Home < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z"></path>
      HTML
    end
  end
end
