# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.1.45
  # * Author: Michael Irigoyen
  class HomeMinusOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14 17H22V19H14V17M5 20V12H2L12 3L22 12H17V10.19L12 5.69L7 10.19V18H12C12 18.7 12.12 19.37 12.34 20H5Z"></path>
      HTML
    end
  end
end
