# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class HomeAlert
    def self.content
      <<-HTML.squish.html_safe
        <path d="M12 3L2 12H5V20H19V12H22L12 3M13 18H11V16H13V18M13 14H11V8H13V14Z"></path>
      HTML
    end
  end
end
