# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.0.39
  # * Author: Google
  class HomeVariantOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,13H15V19H18V10L12,5.5L6,10V19H9V13M4,21V9L12,3L20,9V21H4Z"></path>
      HTML
    end
  end
end
