# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.4.93
  # * Author: GreenTurtwig
  class HomeFloor1 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,3L2,12H5V20H19V12H22L12,3M10,8H14V18H12V10H10V8Z"></path>
      HTML
    end
  end
end
