# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Hospital
    def self.content
      <<-HTML.squish.html_safe
        <path d="M18 14H14V18H10V14H6V10H10V6H14V10H18"></path>
      HTML
    end
  end
end
