# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.8.95
  # * Author: Austin Andrews
  class Identifier < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10 7V9H9V15H10V17H6V15H7V9H6V7H10M16 7C17.11 7 18 7.9 18 9V15C18 16.11 17.11 17 16 17H12V7M16 9H14V15H16V9Z"></path>
      HTML
    end
  end
end
