# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.9.95
  # * Author: Haley Halcyon
  class IdeogramCjk < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 4V6H4V10H6V8H18V10H20V6H13V4M8 10V12H13.59L11.59 14H4V16H11V18H10V20H13V16H20V14H14.21L16 12.21V10Z"></path>
      HTML
    end
  end
end
