# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.2.96
  # * Author: Jeff Anders
  class InformationSlabSymbol < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13 9H11V7H13V9M14 15V17H10V15H11V13H10V11H13V15H14Z"></path>
      HTML
    end
  end
end
