# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.2.96
  # * Author: Jeff Anders
  class InformationSymbol < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 9H13V7H11V9M11 17H13V11H11V17Z"></path>
      HTML
    end
  end
end
