# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.4.47
  # * Author: Jeff Anders
  class Invoice < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21 22L18 20L15 22L12 20L9 22L6 20L3 22V3H21V22Z"></path>
      HTML
    end
  end
end
