# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.4.47
  # * Author: Jeff Anders
  class InvoiceSendOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M24 18L14 13V17L18 18L14 19V23L24 18M19 13.26L21 14.26V3H3V22L6 20L9 22L12 20V17.6L9 19.6L6 17.6L5 18.26V5H19V13.26Z"></path>
      HTML
    end
  end
end
