# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.4.47
  # * Author: Jeff Anders
  class InvoiceArrowLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21 13.34C20.37 13.12 19.7 13 19 13C15.69 13 13 15.69 13 19C13 19.65 13.1 20.28 13.3 20.86L12 20L9 22L6 20L3 22V3H21V13.34M18 18V16L15 19L18 22V20H22V18H18Z"></path>
      HTML
    end
  end
end
