# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.4.47
  # * Author: Jeff Anders
  class InvoiceText < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 3V22L6 20L9 22L12 20L15 22L18 20L21 22V3H3M17 7V9H7V7H17M15 11V13H7V11H15Z"></path>
      HTML
    end
  end
end
