# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class KeyboardF1
    def self.content
      <<-HTML.squish.html_safe
        <path d="M6 7H12V9H8V11H11V13H8V17H6V7M14 7H18V17H16V9H14V7Z"></path>
      HTML
    end
  end
end
