# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Michael Irigoyen
  class KeyboardTabReverse < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4 6H2V18H4M11 6L5 12L11 18L12.41 16.58L8.83 13H23V11H8.83L12.41 7.41L11 6Z"></path>
      HTML
    end
  end
end
