# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.1.95
  # * Author: Michael Richins
  class KeyboardSpace < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 15H5V19H19V15H21V19C21 20.1 20.1 21 19 21H5C3.9 21 3 20.1 3 19V15Z"></path>
      HTML
    end
  end
end
