# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.7.95
  # * Author: Austin Andrews
  class KeyboardF7 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5 7H11V9H7V11H10V13H7V17H5V7M15 17H13L17 9H13V7H19V9L15 17Z"></path>
      HTML
    end
  end
end
