# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.7.95
  # * Author: Austin Andrews
  class KeyboardF4 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5 7H11V9H7V11H10V13H7V17H5V7M13 7H15V11H17V7H19V17H17V13H13V7Z"></path>
      HTML
    end
  end
end
