# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: Augustin Ursu
  class Knife < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20.62,2C23.97,7.61 12.47,20.15 12.47,20.15L9.6,17.28L4.91,22L2.77,19.86L20.62,2Z"></path>
      HTML
    end
  end
end
