# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Lamp < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8,2H16L20,14H4L8,2M11,15H13V20H18V22H6V20H11V15Z"></path>
      HTML
    end
  end
end
