# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.5.55
  # * Author: Michael Irigoyen
  class Lamps < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10 2L12 9H2L4 2M6 10H8V20H11V22H3V20H6V10M20 8L22 15H12L14 8M16 16H18V20H21V22H13V20H16V16Z"></path>
      HTML
    end
  end
end
