# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class LampOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14.56 4L17.23 12H6.78L9.44 4H14.56M16 2H8L4 14H20L16 2M11 15H13V20H18V22H6V20H11V15Z"></path>
      HTML
    end
  end
end
