# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.6.95
  # * Author: Contributors
  class LanguageKotlin < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2 2H22L12 12L22 22H2Z"></path>
      HTML
    end
  end
end
