# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.1.45
  # * Author: Brooke Clifton
  class LightningBolt < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 15H6L13 1V9H18L11 23V15Z"></path>
      HTML
    end
  end
end
