# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class LightningBoltOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 9.47V11H14.76L13 14.53V13H9.24L11 9.47M13 1L6 15H11V23L18 9H13V1Z"></path>
      HTML
    end
  end
end
