# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class LocationExit < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22 12L18 8V11H10V13H18V16M20 18A10 10 0 1 1 20 6H17.27A8 8 0 1 0 17.27 18Z"></path>
      HTML
    end
  end
end
