# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MathNorm
    def self.content
      <<-HTML.squish.html_safe
        <path d="M14 21V3H16V21H14M8 21V3H10V21H8Z"></path>
      HTML
    end
  end
end
