# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.0.96
  # * Author: Michael Irigoyen
  class MathNorm < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14 21V3H16V21H14M8 21V3H10V21H8Z"></path>
      HTML
    end
  end
end
