# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.3.67
  # * Author: Michael Richins
  class MenuClose < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 6H13V8H3V6M3 16H13V18H3V16M3 11H15V13H3V11M16 7L14.58 8.39L18.14 12L14.58 15.61L16 17L21 12L16 7Z"></path>
      HTML
    end
  end
end
