# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MenuRightOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,6H10.5L16.5,12L10.5,18H9V6M13.67,12L11,9.33V14.67L13.67,12Z"></path>
      HTML
    end
  end
end
