# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Austin Andrews
  class MenuRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10,17L15,12L10,7V17Z"></path>
      HTML
    end
  end
end
