# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.7.22
  # * Author: Austin Andrews
  class MenuUpOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18,16V14.5L12,8.5L6,14.5V16H18M12,11.33L14.67,14H9.33L12,11.33Z"></path>
      HTML
    end
  end
end
