# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MenuUp
    def self.content
      <<-HTML.squish.html_safe
        <path d="M7,15L12,10L17,15H7Z"></path>
      HTML
    end
  end
end
