# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.7.22
  # * Author: Austin Andrews
  class MenuDownOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18,9V10.5L12,16.5L6,10.5V9H18M12,13.67L14.67,11H9.33L12,13.67Z"></path>
      HTML
    end
  end
end
