# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class MenuUp < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,15L12,10L17,15H7Z"></path>
      HTML
    end
  end
end
