# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MenuSwap < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,6L7,11H17L12,6M7,13L12,18L17,13H7Z"></path>
      HTML
    end
  end
end
