# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MenuLeft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14,7L9,12L14,17V7Z"></path>
      HTML
    end
  end
end
