# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: Peter Noble
  class MenuLeftOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M15,18H13.5L7.5,12L13.5,6H15V18M10.33,12L13,14.67V9.33L10.33,12Z"></path>
      HTML
    end
  end
end
