# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class MenuDown < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,10L12,15L17,10H7Z"></path>
      HTML
    end
  end
end
