# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Contributors
  class Microsoft < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2,3H11V12H2V3M11,22H2V13H11V22M21,3V12H12V3H21M21,22H12V13H21V22Z"></path>
      HTML
    end
  end
end
