# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MicrosoftDynamics365
    def self.content
      <<-HTML.squish.html_safe
        <path d="M6,2L17.25,8.5L13.5,11.5L6,8V2M6,9L9.5,11.25L6,22L18,9V15L6,22V9Z"></path>
      HTML
    end
  end
end
