# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.1.19
  # * Author: Contributors
  class MicrosoftAzure < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13.05,4.24L6.56,18.05L2,18L7.09,9.24L13.05,4.24M13.75,5.33L22,19.76H6.74L16.04,18.1L11.17,12.31L13.75,5.33Z"></path>
      HTML
    end
  end
end
