# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MinusThick
    def self.content
      <<-HTML.squish.html_safe
        <path d="M20 14H4V10H20V14Z"></path>
      HTML
    end
  end
end
