# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Minus
    def self.content
      <<-HTML.squish.html_safe
        <path d="M19,13H5V11H19V13Z"></path>
      HTML
    end
  end
end
