# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.7.55
  # * Author: Colton Wiscombe
  class MinusThick < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20 14H4V10H20"></path>
      HTML
    end
  end
end
