# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.9.97
  # * Author: Michael Irigoyen
  class MoonNew < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 20A8 8 0 1 1 20 12A8 8 0 0 1 12 20M12 2A10 10 0 1 0 22 12A10 10 0 0 0 12 2Z"></path>
      HTML
    end
  end
end
