# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.9.97
  # * Author: Michael Irigoyen
  class MoonWaningGibbous < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18 12C18 7.5 16.08 3.26 12 2A10 10 0 0 0 12 22C16.08 20.74 18 16.5 18 12Z"></path>
      HTML
    end
  end
end
