# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MoonWaningCrescent < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2 12A10 10 0 0 0 15 21.54A10 10 0 0 1 15 2.46A10 10 0 0 0 2 12Z"></path>
      HTML
    end
  end
end
