# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.9.97
  # * Author: Michael Irigoyen
  class MoonLastQuarter < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 2A10 10 0 0 0 12 22Z"></path>
      HTML
    end
  end
end
