# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MoonLastQuarter
    def self.content
      <<-HTML.squish.html_safe
        <path d="M12 2A10 10 0 0 0 12 22Z"></path>
      HTML
    end
  end
end
