# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.9.97
  # * Author: Michael Irigoyen
  class MoonWaxingCrescent < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 2A9.91 9.91 0 0 0 9 2.46A10 10 0 0 1 9 21.54A10 10 0 1 0 12 2Z"></path>
      HTML
    end
  end
end
