# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.1.95
  # * Author: Colton Wiscombe
  class MortarPestle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21 7L19 13L21 19V21H3V19L5 13L3 7V5H15.7L17.2 1L19.5 1.8L18.3 5H21V7Z"></path>
      HTML
    end
  end
end
