# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class MusicRestHalf < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6 14H8V10H16V14H18V15H6V14Z"></path>
      HTML
    end
  end
end
