# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.9.97
  # * Author: Michael Irigoyen
  class MusicRestWhole < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18 10H16V14H8V10H6V9H18V10Z"></path>
      HTML
    end
  end
end
