# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class NavigationVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21 3L3 10.53V11.5L9.84 14.16L12.5 21H13.46L21 3Z"></path>
      HTML
    end
  end
end
