# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class NetworkStrength3
    def self.content
      <<-HTML.squish.html_safe
        <path d="M1,21H21V1M19,5.83V19H16V8.83"></path>
      HTML
    end
  end
end
