# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class NetworkStrength4
    def self.content
      <<-HTML.squish.html_safe
        <path d="M1,21H21V1"></path>
      HTML
    end
  end
end
