# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class NetworkStrength2 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M1,21H21V1M19,5.83V19H13V11.83"></path>
      HTML
    end
  end
end
