# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.3.50
  # * Author: Simran
  class NetworkStrengthOff < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21,1L12.4,9.6L21,18.19M4.77,4.5L3.5,5.77L9.86,12.13L1,21H18.73L20.73,23L22,21.73"></path>
      HTML
    end
  end
end
