# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.3.50
  # * Author: Simran
  class NetworkStrengthOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M1,21H21V1M19,5.83V19H6"></path>
      HTML
    end
  end
end
