# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.3.50
  # * Author: Simran
  class NetworkStrength4Alert < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19 17H21V11H19M19 21H21V19H19M1 21H17V9H21V1"></path>
      HTML
    end
  end
end
