# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class NetworkStrength2Alert < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21 1L1 21H17V19H13V11.8L19 5.8V9H21M19 11V17H21V11M19 19V21H21V19"></path>
      HTML
    end
  end
end
