# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.4.85
  # * Author: Nick
  class NotEqual < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21,10H9V8H21V10M21,16H9V14H21V16M4,5H6V16H4V5M6,18V20H4V18H6Z"></path>
      HTML
    end
  end
end
