# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class NotificationClearAll < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,13H19V11H5M3,17H17V15H3M7,7V9H21V7"></path>
      HTML
    end
  end
end
