# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.8.94
  # * Author: GreenTurtwig
  class Numeric7 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11,17L15,9V7H9V9H13L9,17"></path>
      HTML
    end
  end
end
