# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.8.94
  # * Author: GreenTurtwig
  class Numeric4 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,7V13H13V17H15V7H13V11H11V7H9Z"></path>
      HTML
    end
  end
end
