# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Numeric1
    def self.content
      <<-HTML.squish.html_safe
        <path d="M10,7V9H12V17H14V7H10Z"></path>
      HTML
    end
  end
end
