# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class NumericPositive1 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13 7V9H15V17H17V7H13M11 13H9V15H7V13H5V11H7V9H9V11H11V13Z"></path>
      HTML
    end
  end
end
