# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Numeric7
    def self.content
      <<-HTML.squish.html_safe
        <path d="M11,17L15,9V7H9V9H13L9,17"></path>
      HTML
    end
  end
end
