# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.8.94
  # * Author: GreenTurtwig
  class Numeric1 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10,7V9H12V17H14V7H10Z"></path>
      HTML
    end
  end
end
