# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Octagon
    def self.content
      <<-HTML.squish.html_safe
        <path d="M15.73,3H8.27L3,8.27V15.73L8.27,21H15.73L21,15.73V8.27"></path>
      HTML
    end
  end
end
