# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.8.36
  # * Author: Austin Andrews
  class PageLayoutSidebarRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,2H18A2,2 0 0,1 20,4V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V4A2,2 0 0,1 6,2M14,8V16H18V8H14Z"></path>
      HTML
    end
  end
end
