# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Pause < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14,19H18V5H14M6,19H10V5H6V19Z"></path>
      HTML
    end
  end
end
