# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Pentagon < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,2.5L2,9.8L5.8,21.5H18.2L22,9.8L12,2.5Z"></path>
      HTML
    end
  end
end
