# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.2.96
  # * Author: Jeff Anders
  class PineTreeVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19 12L12 2L5 12H6.86L3 18H10V22H14V18H21L17.14 12H19Z"></path>
      HTML
    end
  end
end
