# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class PineTree < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10,21V18H3L8,13H5L10,8H7L12,3L17,8H14L19,13H16L21,18H14V21H10Z"></path>
      HTML
    end
  end
end
