# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class PlayOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8.5,8.64L13.77,12L8.5,15.36V8.64M6.5,5V19L17.5,12"></path>
      HTML
    end
  end
end
