# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class PlaylistMinus
    def self.content
      <<-HTML.squish.html_safe
        <path d="M2,16H10V14H2M12,14V16H22V14M14,6H2V8H14M14,10H2V12H14V10Z"></path>
      HTML
    end
  end
end
