# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Play
    def self.content
      <<-HTML.squish.html_safe
        <path d="M8,5.14V19.14L19,12.14L8,5.14Z"></path>
      HTML
    end
  end
end
