# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class Play < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8,5.14V19.14L19,12.14L8,5.14Z"></path>
      HTML
    end
  end
end
