# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class PlayPause < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,5V19L11,12M13,19H16V5H13M18,5V19H21V5"></path>
      HTML
    end
  end
end
