# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.5.95
  # * Author: Austin Andrews
  class PlusThick < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20 14H14V20H10V14H4V10H10V4H14V10H20V14Z"></path>
      HTML
    end
  end
end
