# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class PlusMinus
    def self.content
      <<-HTML.squish.html_safe
        <path d="M11,4V9H6V11H11V16H13V11H18V9H13V4H11M6,18V20H18V18H6Z"></path>
      HTML
    end
  end
end
