# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class Plus < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path>
      HTML
    end
  end
end
