# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.3.67
  # * Author: Contributors
  class Pocket < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4 3H20V17.63L12 22.25L4 17.63V3M18 9H6V16.5L12 19.94L18 16.5V9M18 5H6V7H18V5Z"></path>
      HTML
    end
  end
end
