# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Austin Andrews
  class Poll < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,22V8H7V22H3M10,22V2H14V22H10M17,22V14H21V22H17Z"></path>
      HTML
    end
  end
end
