# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.7.96
  # * Author: benjocaz45
  class PostLamp < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14 3L13 1H11L10 3L5 6H7L8 14L10 16L10.5 17H9V23H15V17H13.5L14 16L16 14L17 6H19L14 3M14.16 13H9.84L9 6H15L14.16 13Z"></path>
      HTML
    end
  end
end
