# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.3.50
  # * Author: Michael Richins
  class PowerOn < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11,3H13V21H11V3Z"></path>
      HTML
    end
  end
end
