# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class PowerOn
    def self.content
      <<-HTML.squish.html_safe
        <path d="M11,3H13V21H11V3Z"></path>
      HTML
    end
  end
end
