# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.1.95
  # * Author: Michael Richins
  class PrinterPos < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18 10H6A2 2 0 0 0 4 12V19H20V12A2 2 0 0 0 18 10M18 14H14V12H18M17 9H7V4H17Z"></path>
      HTML
    end
  end
end
