# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.1.96
  # * Author: Colton Wiscombe
  class PrinterPosOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18 10H17V4H7V10H6C4.89 10 4 10.9 4 12V19H20V12C20 10.9 19.11 10 18 10M9 6H15V10H9V6M18 17H6V12H18V17M17 15H13V13H17V15Z"></path>
      HTML
    end
  end
end
