# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.1.95
  # * Author: pp81381
  class ProjectorScreenVariantOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20 6H4C3.45 6 3 6.45 3 7V8C3 8.55 3.45 9 4 9H5V18H19V9H20C20.55 9 21 8.55 21 8V7C21 6.45 20.55 6 20 6M17 16H7V9H17V16Z"></path>
      HTML
    end
  end
end
