# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Publish < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,4V6H19V4H5M5,14H9V20H15V14H19L12,7L5,14Z"></path>
      HTML
    end
  end
end
