# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.3.67
  # * Author: mschutti
  class QueueFirstInLastOut < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6 6H18V8H6V6M6 10.5H18V12.5H6V10.5M6 15H18V17H6V15M9 19H15L12 22L9 19M9 2H15L12 5L9 2Z"></path>
      HTML
    end
  end
end
