# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class RectangleOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M4,6V19H20V6H4M18,17H6V8H18V17Z"></path>
      HTML
    end
  end
end
