# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.6.95
  # * Author: Terren
  class Rectangle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,6V19H20V6H4Z"></path>
      HTML
    end
  end
end
