# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.3.45
  # * Author: Michael Richins
  class RelationOneOrManyToOnlyOne < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22 15V17H21V19H19V17H18V19H16V17H11V9H7V11H5V9L3 11H2V5H3L5 7V5H7V7H13V15H16V13H18V15H19V13H21V15Z"></path>
      HTML
    end
  end
end
