# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.3.45
  # * Author: Michael Richins
  class RelationManyToMany < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22 13V19H21L19 17H11V9H5L3 11H2V5H3L5 7H13V15H19L21 13Z"></path>
      HTML
    end
  end
end
