# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class RelationManyToOne
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22 15V17H19V19H17V17H11V9H5L3 11H2V5H3L5 7H13V15H17V13H19V15Z"></path>
      HTML
    end
  end
end
