# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class RelationOneToOneOrMany
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22 13V19H21L19 17V19H17V17H11V9H7V11H5V9H2V7H5V5H7V7H13V15H17V13H19V15L21 13Z"></path>
      HTML
    end
  end
end
