# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class RelationOnlyOneToOne
    def self.content
      <<-HTML.squish.html_safe
        <path d="M22 15V17H19V19H17V17H11V9H8V11H6V9H5V11H3V9H2V7H3V5H5V7H6V5H8V7H13V15H17V13H19V15Z"></path>
      HTML
    end
  end
end
