# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.3.45
  # * Author: Michael Richins
  class RelationOneOrManyToMany < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22 13V19H21L19 17H11V9H7V11H5V9L3 11H2V5H3L5 7V5H7V7H13V15H19L21 13Z"></path>
      HTML
    end
  end
end
