# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class RelationOneToOne < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22 15V17H19V19H17V17H11V9H7V11H5V9H2V7H5V5H7V7H13V15H17V13H19V15Z"></path>
      HTML
    end
  end
end
