# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ReorderVertical
    def self.content
      <<-HTML.squish.html_safe
        <path d="M9,3V21H11V3H9M5,3V21H7V3H5M13,3V21H15V3H13M19,3H17V21H19V3Z"></path>
      HTML
    end
  end
end
