# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.7.12
  # * Author: Google
  class ReorderHorizontal < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,15H21V13H3V15M3,19H21V17H3V19M3,11H21V9H3V11M3,5V7H21V5H3Z"></path>
      HTML
    end
  end
end
