# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.8.94
  # * Author: Louistwee
  class Resistor < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2,11H7L10.07,15.35L13.11,4L18,11H22V13H17L13.93,8.65L10.89,20L6,13H2V11Z"></path>
      HTML
    end
  end
end
