# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class Rewind < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11.5,12L20,18V6M11,18V6L2.5,12L11,18Z"></path>
      HTML
    end
  end
end
