# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.2.95
  # * Author: Michael Irigoyen
  class RomanNumeral7 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4 7L6 17H8L10 7H8L7 12L6 7H4M15 7V9H14V15H15V17H11V15H12V9H11V7H15M20 7V9H19V15H20V17H16V15H17V9H16V7H20Z"></path>
      HTML
    end
  end
end
