# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class RomanNumeral4 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 7L14 17H16L18 7H16L15 12L14 7H12M11 7V9H10V15H11V17H7V15H8V9H7V7H11Z"></path>
      HTML
    end
  end
end
