# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.2.95
  # * Author: Contributors
  class RomanNumeral10 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9 7L11 12L9 17H11L12 14.5L13 17H15L13 12L15 7H13L12 9.5L11 7H9Z"></path>
      HTML
    end
  end
end
