# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.2.45
  # * Author: Haley Halcyon
  class SawtoothWave < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 22V6.83L2 16V13.17L13 2V17.17L22 8V10.83L11 22Z"></path>
      HTML
    end
  end
end
