# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.7.94
  # * Author: Google
  class Segment < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21,8H3V6H21M9,13H21V11H9M9,18H21V16H9"></path>
      HTML
    end
  end
end
