# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.2.96
  # * Author: Google
  class SendVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 20V14L11 12L3 10V4L22 12Z"></path>
      HTML
    end
  end
end
