# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.2.96
  # * Author: Google
  class SendVariantOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 20V4L22 12M5 17L16.85 12L5 7V10.5L11 12L5 13.5M5 17V7 13.5Z"></path>
      HTML
    end
  end
end
