# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Send < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2,21L23,12L2,3V10L17,12L2,14V21Z"></path>
      HTML
    end
  end
end
