# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SettingsHelper < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,22H9V24H7V22M11,22H13V24H11V22M15,22H17V24H15V22Z"></path>
      HTML
    end
  end
end
