# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ShapeSquarePlus < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,5H22V7H19V10H17V7H14V5H17V2H19V5M17,19V13H19V21H3V5H11V7H5V19H17Z"></path>
      HTML
    end
  end
end
