# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ShapeRectanglePlus < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,6H22V8H19V11H17V8H14V6H17V3H19V6M17,17V14H19V19H3V6H11V8H5V17H17Z"></path>
      HTML
    end
  end
end
