# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.7.94
  # * Author: Peter Noble
  class ShieldAlert < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,1L3,5V11C3,16.55 6.84,21.74 12,23C17.16,21.74 21,16.55 21,11V5M11,7H13V13H11M11,15H13V17H11"></path>
      HTML
    end
  end
end
