# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.9.95
  # * Author: Michael Irigoyen
  class ShieldHalf < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 1L3 5V11C3 16.5 6.8 21.7 12 23V1Z"></path>
      HTML
    end
  end
end
