# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.2.89
  # * Author: Michael Irigoyen
  class ShieldCross < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,1L3,5V11C3,16.5 6.8,21.7 12,23C17.2,21.7 21,16.5 21,11V5L12,1M16,10H13V18H11V10H8V8H11V5H13V8H16V10Z"></path>
      HTML
    end
  end
end
