# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ShuffleDisabled
    def self.content
      <<-HTML.squish.html_safe
        <path d="M16,4.5V7H5V9H16V11.5L19.5,8M16,12.5V15H5V17H16V19.5L19.5,16"></path>
      HTML
    end
  end
end
