# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SignPole < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 3L12 2L13 3V20C14.11 20 15 20.9 15 22H9C9 20.9 9.9 20 11 20V3Z"></path>
      HTML
    end
  end
end
