# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SignalCellular3
    def self.content
      <<-HTML.squish.html_safe
        <path d="M21,4H16V20H21V4M14,9H9V20H14V9M7,14H2V20H7V14Z"></path>
      HTML
    end
  end
end
