# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.3.92
  # * Author: Michael Irigoyen
  class SkewLess < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M17.5,11L15.41,20H10.5L12.59,11H17.5M20,9H11L8,22H17L20,9M4,6L8,2V5H16V7H8V10L4,6Z"></path>
      HTML
    end
  end
end
