# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class SkipNext < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M16,18H18V6H16M6,18L14.5,12L6,6V18Z"></path>
      HTML
    end
  end
end
