# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Simran
  class SkipForward < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,5V19L11,12M18,5V19H20V5M11,5V19L18,12"></path>
      HTML
    end
  end
end
