# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SkipNext
    def self.content
      <<-HTML.squish.html_safe
        <path d="M16,18H18V6H16M6,18L14.5,12L6,6V18Z"></path>
      HTML
    end
  end
end
