# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SkipForward
    def self.content
      <<-HTML.squish.html_safe
        <path d="M4,5V19L11,12M18,5V19H20V5M11,5V19L18,12"></path>
      HTML
    end
  end
end
