# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SkipBackward
    def self.content
      <<-HTML.squish.html_safe
        <path d="M20,5V19L13,12M6,5V19H4V5M13,5V19L6,12"></path>
      HTML
    end
  end
end
