# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Simran
  class SkipBackward < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20,5V19L13,12M6,5V19H4V5M13,5V19L6,12"></path>
      HTML
    end
  end
end
