# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.8.95
  # * Author: Michael Irigoyen
  class SkipPreviousOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,6H8V18H6M9.5,12L18,18V6M16,14.14L12.97,12L16,9.86V14.14Z"></path>
      HTML
    end
  end
end
