# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SkipNextOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,18L14.5,12L6,6M8,9.86L11.03,12L8,14.14M16,6H18V18H16"></path>
      HTML
    end
  end
end
