# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SkipBackwardOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M18,14.17L15.83,12L18,9.83V14.17M20,19V5L13,12M4,19H6V5H4M11,14.17L8.83,12L11,9.83V14.17M13,19V5L6,12"></path>
      HTML
    end
  end
end
