# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.6.50
  # * Author: Simran
  class SkipNextCircle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M8,8L13,12L8,16M14,8H16V16H14"></path>
      HTML
    end
  end
end
