# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class SkipPrevious < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,18V6H8V18H6M9.5,12L18,6V18L9.5,12Z"></path>
      HTML
    end
  end
end
