# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SlashForward
    def self.content
      <<-HTML.squish.html_safe
        <path d="M7 21L14.9 3H17L9.1 21H7Z"></path>
      HTML
    end
  end
end
