# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.0.96
  # * Author: Michael Irigoyen
  class SlashForward < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7 21L14.9 3H17L9.1 21H7Z"></path>
      HTML
    end
  end
end
