# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.7.12
  # * Author: Austin Andrews
  class Solid < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M0,0H24V24H0"></path>
      HTML
    end
  end
end
