# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Solid
    def self.content
      <<-HTML.squish.html_safe
        <path d="M0,0H24V24H0"></path>
      HTML
    end
  end
end
