# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: frankgrinaert
  class SortDescending < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19 7H22L18 3L14 7H17V21H19M2 17H12V19H2M6 5V7H2V5M2 11H9V13H2V11Z"></path>
      HTML
    end
  end
end
