# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Simran
  class SortReverseVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 11H15V13H3M3 18V16H21V18M3 6H9V8H3Z"></path>
      HTML
    end
  end
end
