# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class SortVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,13H15V11H3M3,6V8H21V6M3,18H9V16H3V18Z"></path>
      HTML
    end
  end
end
