# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SortReverseVariant
    def self.content
      <<-HTML.squish.html_safe
        <path d="M3 11H15V13H3M3 18V16H21V18M3 6H9V8H3Z"></path>
      HTML
    end
  end
end
