# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Spear < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M16 9H16.41L3.41 22L2 20.59L15 7.59V9H16M16 4V8H20L22 2L16 4Z"></path>
      HTML
    end
  end
end
