# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.4.55
  # * Author: Jeff Anders
  class SquareRounded < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8 3H16C18.76 3 21 5.24 21 8V16C21 18.76 18.76 21 16 21H8C5.24 21 3 18.76 3 16V8C3 5.24 5.24 3 8 3Z"></path>
      HTML
    end
  end
end
