# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.9.32
  # * Author: Austin Andrews
  class SquareOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,3H21V21H3V3M5,5V19H19V5H5Z"></path>
      HTML
    end
  end
end
