# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SquareMedium
    def self.content
      <<-HTML.squish.html_safe
        <path d="M16,8H8V16H16V8Z"></path>
      HTML
    end
  end
end
