# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.4.55
  # * Author: Michael Irigoyen
  class SquareCircle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20 4V20H4V4H20M22 2H2V22H22V2M12 6C8.69 6 6 8.69 6 12S8.69 18 12 18 18 15.31 18 12 15.31 6 12 6Z"></path>
      HTML
    end
  end
end
