# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: Michael Irigoyen
  class SquareMediumOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14,10V14H10V10H14M16,8H8V16H16V8Z"></path>
      HTML
    end
  end
end
