# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.5.94
  # * Author: Michael Irigoyen
  class SquareSmall < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10,14V10H14V14H10Z"></path>
      HTML
    end
  end
end
