# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SquareWave < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M2 2V12H4V4H11V22H22V12H20V20H13V2H2Z"></path>
      HTML
    end
  end
end
