# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.9.32
  # * Author: Austin Andrews
  class Square < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,3V21H21V3"></path>
      HTML
    end
  end
end
