# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Stairs
    def self.content
      <<-HTML.squish.html_safe
        <path d="M15,5V9H11V13H7V17H3V20H10V16H14V12H18V8H22V5H15Z"></path>
      HTML
    end
  end
end
