# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Simran
  class StarHalf < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 2L9.19 8.62L2 9.24L7.45 13.97L5.82 21L12 17.27V2Z"></path>
      HTML
    end
  end
end
