# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.2.96
  # * Author: Jeff Anders
  class StarFourPointsSmall < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10.74 10.75L12 8L13.25 10.75L16 12L13.25 13.26L12 16L10.74 13.26L8 12L10.74 10.75Z"></path>
      HTML
    end
  end
end
