# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class StarThreePoints < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,2.6L9,12.4L2,19.9L12,17.6L22,20L15,12.5L12,2.6Z"></path>
      HTML
    end
  end
end
