# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.7.94
  # * Author: Michael Irigoyen
  class StarFourPointsOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,6.7L13.45,10.55L17.3,12L13.45,13.45L12,17.3L10.55,13.45L6.7,12L10.55,10.55L12,6.7M12,1L9,9L1,12L9,15L12,23L15,15L23,12L15,9L12,1Z"></path>
      HTML
    end
  end
end
