# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.7.94
  # * Author: Michael Irigoyen
  class StarFourPoints < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12,1L9,9L1,12L9,15L12,23L15,15L23,12L15,9L12,1Z"></path>
      HTML
    end
  end
end
