# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Simran
  class StepForward < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M5,5V19H8V5M10,5V19L21,12"></path>
      HTML
    end
  end
end
