# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class StepBackward2
    def self.content
      <<-HTML.squish.html_safe
        <path d="M17,5H14V19H17V5M12,5L1,12L12,19V5M22,5H19V19H22V5Z"></path>
      HTML
    end
  end
end
