# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Simran
  class StepBackward < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,5V19H16V5M14,5V19L3,12"></path>
      HTML
    end
  end
end
