# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class StepForward2
    def self.content
      <<-HTML.squish.html_safe
        <path d="M7,5H10V19H7V5M12,5L23,12L12,19V5M2,5H5V19H2V5Z"></path>
      HTML
    end
  end
end
