# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Stop < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18,18H6V6H18V18Z"></path>
      HTML
    end
  end
end
