# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.9.95
  # * Author: Google
  class StoreOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18.36 9L18.96 12H5.04L5.64 9H18.36M20 4H4V6H20V4M20 7H4L3 12V14H4V20H14V14H18V20H20V14H21V12L20 7M6 18V14H12V18H6Z"></path>
      HTML
    end
  end
end
