# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SubdirectoryArrowLeft
    def self.content
      <<-HTML.squish.html_safe
        <path d="M11,9L12.42,10.42L8.83,14H18V4H20V16H8.83L12.42,19.58L11,21L5,15L11,9Z"></path>
      HTML
    end
  end
end
