# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SubdirectoryArrowRight < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19,15L13,21L11.58,19.58L15.17,16H4V4H6V14H15.17L11.58,10.42L13,9L19,15Z"></path>
      HTML
    end
  end
end
