# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SurroundSound71
    def self.content
      <<-HTML.squish.html_safe
        <path d="M14 17H12V15H14V17M20 7V17H18V9H16V7H20M4 17L8 9H4V7H10V9L6 17"></path>
      HTML
    end
  end
end
