# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class SwapVerticalBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M14,8H11V14H6V8H3L8.5,2L14,8M15.5,22L21,16H18V10H13V16H10L15.5,22Z"></path>
      HTML
    end
  end
end
