# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.0.39
  # * Author: Google
  class SwapHorizontalBold < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8,10V13H14V18H8V21L2,15.5L8,10M22,8.5L16,3V6H10V11H16V14L22,8.5Z"></path>
      HTML
    end
  end
end
