# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.1.95
  # * Author: Michael Richins
  class TableChair < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 22H6A2 2 0 0 1 8 20V8H2V5H16V8H10V20A2 2 0 0 1 12 22M22 2V22H20V15H15V22H13V14A2 2 0 0 1 15 12H20V2Z"></path>
      HTML
    end
  end
end
