# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.8.96
  # * Author: Michael Irigoyen
  class TallyMark1 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13 19H11V5H13V19Z"></path>
      HTML
    end
  end
end
