# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.8.96
  # * Author: Michael Irigoyen
  class TallyMark4 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7 19H5V5H7V19M11 5H9V19H11V5M15 5H13V19H15V5M19 5H17V19H19V5Z"></path>
      HTML
    end
  end
end
