# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.8.96
  # * Author: Michael Irigoyen
  class TallyMark3 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9 19H7V5H9V19M13 5H11V19H13V5M17 5H15V19H17V5Z"></path>
      HTML
    end
  end
end
