# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.8.96
  # * Author: Michael Irigoyen
  class TallyMark2 < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M11 19H9V5H11V19M15 5H13V19H15V5Z"></path>
      HTML
    end
  end
end
