# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class TemperatureKelvin
    def self.content
      <<-HTML.squish.html_safe
        <path d="M7,5H10V11L15,5H19L13.88,10.78L19,20H15.38L11.76,13.17L10,15.15V20H7V5Z"></path>
      HTML
    end
  end
end
