# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.3.50
  # * Author: Austin Andrews
  class TestTubeEmpty < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,2H17V4H16V18A4,4 0 0,1 12,22A4,4 0 0,1 8,18V4H7V2M14,4H10V18A2,2 0 0,0 12,20A2,2 0 0,0 14,18V4Z"></path>
      HTML
    end
  end
end
