# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.4.85
  # * Author: Google
  class TextLong < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,5H20V7H4V5M4,9H20V11H4V9M4,13H20V15H4V13M4,17H14V19H4V17Z"></path>
      HTML
    end
  end
end
