# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Text < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21,6V8H3V6H21M3,18H12V16H3V18M3,13H21V11H3V13Z"></path>
      HTML
    end
  end
end
