# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class TextShort < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,9H20V11H4V9M4,13H14V15H4V13Z"></path>
      HTML
    end
  end
end
