# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Tie < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,2L10,6L7,17L12,22L17,17L14,6L18,2Z"></path>
      HTML
    end
  end
end
