# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class TimerSandFull < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M6,2V8H6V8L10,12L6,16V16H6V22H18V16H18V16L14,12L18,8V8H18V2H6Z"></path>
      HTML
    end
  end
end
