# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.9.96
  # * Author: Colton Wiscombe
  class TrainCarContainer < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M1 6V17H2C2 18.11 2.9 19 4 19S6 18.11 6 17H18C18 18.11 18.9 19 20 19S22 18.11 22 17H23V6H1M21 15H19V9H17V15H15V9H13V15H11V9H9V15H7V9H5V15H3V8H21V15Z"></path>
      HTML
    end
  end
end
