# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.9.96
  # * Author: Colton Wiscombe
  class TrainCarFlatbed < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M23 15V17H22C22 18.11 21.11 19 20 19S18 18.11 18 17H6C6 18.11 5.11 19 4 19S2 18.11 2 17H1V15H23Z"></path>
      HTML
    end
  end
end
