# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.9.96
  # * Author: Colton Wiscombe
  class TrainCarHopper < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M1 8V17H2C2 18.11 2.9 19 4 19S6 18.11 6 17H18C18 18.11 18.9 19 20 19S22 18.11 22 17H23V8H1M13 15V11H11V15H8V11H6V15H3V10H21V15H18V11H16V15H13Z"></path>
      HTML
    end
  end
end
