# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class TransferLeft
    def self.content
      <<-HTML.squish.html_safe
        <path d="M21,16H19V8H21V16M17,16H15V8H17V16M13,16H11V8H13V16M9,5V19L2,12L9,5Z"></path>
      HTML
    end
  end
end
