# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.4.93
  # * Author: Michael Richins
  class TransferUp < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M8,21V19H16V21H8M8,17V15H16V17H8M8,13V11H16V13H8M19,9H5L12,2L19,9Z"></path>
      HTML
    end
  end
end
