# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 2.6.95
  # * Author: GreenTurtwig
  class TrashCan < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9,3V4H4V6H5V19A2,2 0 0,0 7,21H17A2,2 0 0,0 19,19V6H20V4H15V3H9M9,8H11V17H9V8M13,8H15V17H13V8Z"></path>
      HTML
    end
  end
end
