# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class TrendingNeutral < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22,12L18,8V11H3V13H18V16L22,12Z"></path>
      HTML
    end
  end
end
