# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Triangle < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M1,21H23L12,2"></path>
      HTML
    end
  end
end
