# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.2.96
  # * Author: Jeff Anders
  class TriangleDownOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M12 22L1 3H23M12 18L19.53 5H4.47"></path>
      HTML
    end
  end
end
