# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class TriangleSmallUp
    def self.content
      <<-HTML.squish.html_safe
        <path d="M8 15H16L12 8"></path>
      HTML
    end
  end
end
