# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class TriangleWave < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M22 12L17 22L7.1 6.04L4.24 12H2L7 2L16.9 17.96L19.76 12H22Z"></path>
      HTML
    end
  end
end
