# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.2.96
  # * Author: Jeff Anders
  class TriangleDown < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M1 3H23L12 22"></path>
      HTML
    end
  end
end
