# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class TriangleOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M12,2L1,21H23M12,6L19.53,19H4.47"></path>
      HTML
    end
  end
end
