# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class Triforce
    def self.content
      <<-HTML.squish.html_safe
        <path d="M1.5,21L12,3.5L22.5,21H1.5M12,21L17,12H7L12,21Z"></path>
      HTML
    end
  end
end
