# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.9.32
  # * Author: Austin Andrews
  class UnfoldMoreVertical < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M18.17,12L15,8.83L16.41,7.41L21,12L16.41,16.58L15,15.17L18.17,12M5.83,12L9,15.17L7.59,16.59L3,12L7.59,7.42L9,8.83L5.83,12Z"></path>
      HTML
    end
  end
end
