# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class UploadMultiple
    def self.content
      <<-HTML.squish.html_safe
        <path d="M9,14V8H5L12,1L19,8H15V14H9M5,18V16H19V18H5M19,20H5V22H19V20Z"></path>
      HTML
    end
  end
end
