# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 7.0.96
  # * Author: Andrea Antonello
  class VectorPointPlus < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M9 9V15H15V9H9M11 11H13V13H11V11M18 15V18H15V20H18V23H20V20H23V18H20V15H18Z"></path>
      HTML
    end
  end
end
