# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewQuilt < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M10,5V11H21V5M16,18H21V12H16M4,18H9V5H4M10,18H15V12H10V18Z"></path>
      HTML
    end
  end
end
