# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.8.36
  # * Author: Michael Irigoyen
  class ViewParallel < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M19 3V21H15V3H19M14 3V21H10V3H14M9 3V21H5V3H9Z"></path>
      HTML
    end
  end
end
