# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewStreamOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M4 6V18H21V6H4M19 16H6V13H19V16M6 11V8H19V11H6Z"></path>
      HTML
    end
  end
end
