# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewSequential
    def self.content
      <<-HTML.squish.html_safe
        <path d="M3 5H21V9H3V5M3 10H21V14H3V10M3 15H21V19H3V15Z"></path>
      HTML
    end
  end
end
