# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewCarouselOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M2 6H6V17H2V6M7 19H17V4H7V19M9 6H15V17H9V6M18 6H22V17H18V6Z"></path>
      HTML
    end
  end
end
