# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 5.3.45
  # * Author: Google
  class ViewQuiltOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4 5V18H21V5H4M6 16V7H9V16H6M11 16V12.5H14V16H11M19 16H16V12.5H19V16M11 10.5V7H19V10.5H11Z"></path>
      HTML
    end
  end
end
