# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewCompactOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,5V19H22V5H3M5,7H20V11H5V7M5,17V13H9V17H5M11,17V13H20V17H11Z"></path>
      HTML
    end
  end
end
