# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.6.95
  # * Author: Google
  class ViewCompact < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,19H9V12H3V19M10,19H22V12H10V19M3,5V11H22V5H3Z"></path>
      HTML
    end
  end
end
