# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewColumn
    def self.content
      <<-HTML.squish.html_safe
        <path d="M16,5V18H21V5M4,18H9V5H4M10,18H15V5H10V18Z"></path>
      HTML
    end
  end
end
