# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewSplitHorizontal
    def self.content
      <<-HTML.squish.html_safe
        <path d="M3,5H21V7H3V5M3,11V9H21V11H3M3,19V13H21V19H3Z"></path>
      HTML
    end
  end
end
