# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewParallelOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M19 3H5V21H19V3M17 19H15V5H17V19M13 19H11V5H13V19M7 5H9V19H7V5Z"></path>
      HTML
    end
  end
end
