# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewCarousel
    def self.content
      <<-HTML.squish.html_safe
        <path d="M18,6V17H22V6M2,17H6V6H2M7,19H17V4H7V19Z"></path>
      HTML
    end
  end
end
