# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewArray
    def self.content
      <<-HTML.squish.html_safe
        <path d="M8,18H17V5H8M18,5V18H21V5M4,18H7V5H4V18Z"></path>
      HTML
    end
  end
end
