# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewArrayOutline
    def self.content
      <<-HTML.squish.html_safe
        <path d="M15 7V16H10V7H15M21 5H18V18H21V5M17 5H8V18H17V5M7 5H4V18H7V5Z"></path>
      HTML
    end
  end
end
