# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewSequentialOutline < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 5V19H21V5H3M19 7V9H5V7H19M19 11V13H5V11H19M5 17V15H19V17H5Z"></path>
      HTML
    end
  end
end
