# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 3.0.39
  # * Author: Google
  class ViewSplitVertical < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M13,5H21V19H13V5M3,5H11V7H3V5M3,11V9H11V11H3M3,19V17H11V19H3M3,15V13H11V15H3Z"></path>
      HTML
    end
  end
end
