# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class ViewStream < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,5V11H21V5M4,18H21V12H4V18Z"></path>
      HTML
    end
  end
end
