# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Google
  class VolumeLow < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M7,9V15H11L16,20V4L11,9H7Z"></path>
      HTML
    end
  end
end
