# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class VolumeSource < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 9V15H7L12 20V4L7 9H3M16 15H14V9H16V15M20 19H18V5H20V19Z"></path>
      HTML
    end
  end
end
