# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.9.32
  # * Author: Austin Andrews
  class VolumeMinus < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3,9H7L12,4V20L7,15H3V9M14,11H22V13H14V11Z"></path>
      HTML
    end
  end
end
