# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 6.9.96
  # * Author: Ron Schaeffer
  class VolumeEqual < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 9H7L12 4V20L7 15H3V9M14 13H22V15H14M14 9H22V11H14Z"></path>
      HTML
    end
  end
end
