# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class WallSconce
    def self.content
      <<-HTML.squish.html_safe
        <path d="M11,4L7,13H19L15,4H11M4,14V22H6V19H14V14H12V17H6V14H4Z"></path>
      HTML
    end
  end
end
