# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class WindowRestore < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M4,8H8V4H20V16H16V20H4V8M16,8V14H18V6H10V8H16M6,12V18H14V12H6Z"></path>
      HTML
    end
  end
end
