# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 1.5.54
  # * Author: Austin Andrews
  class WindowMinimize < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M20,14H4V10H20"></path>
      HTML
    end
  end
end
