# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class WindowMaximize
    def self.content
      <<-HTML.squish.html_safe
        <path d="M4,4H20V20H4V4M6,8V18H18V8H6Z"></path>
      HTML
    end
  end
end
