# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  # * Version: 4.5.95
  # * Author: Michael Richins
  class WindowClosedVariant < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M21 20V2H3V20H1V23H23V20M19 4V11H13V4M5 4H11V11H5M5 20V13H11V20M13 20V13H19V20Z"></path>
      HTML
    end
  end
end
