# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class WindowShutterOpen < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M3 4H21V8H19V20H17V8H7V20H5V8H3V4M8 9H16V11H8V9Z"></path>
      HTML
    end
  end
end
