# frozen_string_literal: true

#
# This file is auto-generated by ./bin/rails mdi:generate
#
module Mdi
  class WrapDisabled < MdiData
    def content
      <<-HTML.squish.html_safe
        <path d="M16,7H3V5H16V7M3,19H16V17H3V19M22,12L18,9V11H3V13H18V15L22,12Z"></path>
      HTML
    end
  end
end
