namespace :mdi do
  desc 'Create auto-generated icon data files models/mdi/*.rb'
  task :generate do
    auto_generated_comment = <<~HEREDOC
      # frozen_string_literal: true

      #
      # This file is auto-generated by ./bin/rails mdi:generate
      #
    HEREDOC

    Dir['config/svg/**/*.svg'].each do |svg_icon_path|
      icon_data_file_name = File.basename(svg_icon_path, '.svg').underscore
      icon_data_file_path = "app/models/mdi/#{icon_data_file_name}.rb"
      puts "Generating #{icon_data_file_path}"
      File.open(icon_data_file_path, 'w+') do |index|
        svg = Nokogiri::HTML.parse(File.read(svg_icon_path))
        svg_content = svg.at_css('svg').children

        File.read(svg_icon_path)
        index.puts auto_generated_comment
        index.puts 'module Mdi'
        index.puts "  class #{icon_data_file_name.camelize}"
        index.puts '    def self.content'
        index.puts '      <<-HTML.squish.html_safe'
        index.puts "        #{svg_content}"
        index.puts '      HTML'
        index.puts '    end'
        index.puts '  end'
        index.puts 'end'
      end
    end
  end
end