# frozen_string_literal: true

namespace :mdi do
  desc 'Create auto-generated icon data files models/mdi/*.rb'
  task :generate do
    auto_generated_comment = <<~HEREDOC
      # frozen_string_literal: true

      #
      # This file is auto-generated by ./bin/rails mdi:generate
      #
    HEREDOC

    Dir['config/svg/*.svg'].each do |svg_icon_path|
      icon_data_file_name = File.basename(svg_icon_path, '.svg').underscore
      icon_data_file_path = "app/models/mdi/#{icon_data_file_name}.rb"
      puts "Generating #{icon_data_file_path}"
      File.open(icon_data_file_path, 'w+') do |f|
        svg = Nokogiri::HTML.parse(File.read(svg_icon_path))
        svg_content = svg.at_css('svg').children

        f.puts auto_generated_comment
        f.puts 'module Mdi'
        f.puts "  class #{icon_data_file_name.camelize} < MdiData"
        f.puts '    def content'
        f.puts '      <<-HTML.squish.html_safe'
        f.puts "        #{svg_content}"
        f.puts '      HTML'
        f.puts '    end'
        f.puts '  end'
        f.puts 'end'
        f
      end
    end
  end
end