require: rubocop-rails

AllCops:
  Exclude:
    - bin/**
    - test/dummy/bin/**
    - config.ru

Style/Documentation:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/BlockLength:
  Max: 80